
#    - name: Install docker and docker compose
# https://github.com/moovs/docker-with-ansible/blob/master/roles/docker/main.yml
- hosts: mata3
  become: true
  vars_files:
    - vars/mata3-vars.yml
  roles:
    - server_initialization
    - docker_setup

  tasks:
#    - name: Copy website files to the server's document root
#    - name: Copy compose.yaml file
#      copy:
#        src: /home/disooqi/projects/A2-Crawler/compose-test.yml
#        dest: "{{ docker_compose_dir }}/{{ docker_compose_file }}"
#        mode: preserve
    - name: copy 'compose.yaml' and '.env' items
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: preserve
      loop:
        - src: "{{ project_dir }}/compose.test.yml"
          dest: "{{ base_dir }}/{{ docker_compose_file }}"
        - src: "{{ project_dir }}/.env.test"
          dest: "{{ base_dir }}/.env.test"
#        - src: dynamic
#          dest: "{{ var_path }}"

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: "{{ base_dir }}"
        env_file: .env.test
        state: absent
#
    - name: Docker compose build and then up
      community.docker.docker_compose:
        project_src: "{{ base_dir }}"
#        env_file: .env
        build: true
        remove_orphans: true
        state: present
      register: output

    - name: Show results
      ansible.builtin.debug:
        var: output

