---

create_user: a2-user
docker_compose_dir: /home/a2-user
docker_compose_file: compose.yaml
env_var_file: .env
#open_port: 8000

copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'vim', 'git', 'ufw']
