- name: Update apt and install Nginx
  apt:
    name:
      - nginx
    state: latest
#        state: absent  # to remove the packages
    update_cache: true

- name: UFW - Allow HTTP connections
  community.general.ufw:
    rule: allow
    name: 'Nginx HTTP'

- name: Create a directory for site if it does not exist
  ansible.builtin.file:
    path: /var/www/{{ domain_name }}/html
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: '0755'

- name: Copy html file for site
  tags: nginx,html
  copy:
    src: home_page.html
    dest: /var/www/{{ domain_name }}/html/index.html
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
#    mode: 0644

#- name: Create a server block
#  tags: nginx
#  template:
#    src: "{{ configuration_block_file }}"
#    dest: /etc/nginx/sites-available/{{ domain_name }}
#    owner: root
#    group: root
#    mode: 0644
#  notify: restart_nginx
#
## ln -s /etc/nginx/sites-available/your_domain /etc/nginx/sites-enabled/
#- name: Create a symbolic link for server block
#  ansible.builtin.file:
#    src: /etc/nginx/sites-available/{{ domain_name }}
#    dest: /etc/nginx/sites-enabled/{{ domain_name }}
#    owner: root
#    group: root
#    state: link
#  notify: restart_nginx

- name: Enable server_names_hash_bucket_size
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    # # server_names_hash_bucket_size 64;
    regexp: '#?\s*server_names_hash_bucket_size'
    line: 'server_names_hash_bucket_size 64;'
  notify: restart_nginx

- name: Restart Nginx, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted

